name = "LnFinder"
uuid = "73725636-0de0-4a56-af23-f9f108662c97"
authors = ["Stijn Peeters <58211004+microstijn@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BioSequences = "3.5.0"
CSV = "0.10.15"
DataFrames = "1.8.1"
FASTX = "2.1.7"
Revise = "3.13.1"
Test = "1.11.0"
