name = "LnFinder"
uuid = "73725636-0de0-4a56-af23-f9f108662c97"
authors = ["Stijn Peeters <58211004+microstijn@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Taxonomy = "10bb16a4-4bfc-432e-9419-4ca69c1a753c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BioSequences = "3.5.0"
CSV = "0.10.15"
CodecZlib = "0.7.8"
DataFrames = "1.8.1"
FASTX = "2.1.7"
HTTP = "1.10.19"
HypothesisTests = "0.11.6"
JSON = "1.4.0"
JSON3 = "1.14.3"
Latexify = "0.16.10"
Markdown = "1.11.0"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Revise = "3.13.1"
Statistics = "1.11.1"
Taxonomy = "0.4.6"
Test = "1.11.0"
